### ISSUE TITLE
starý preklad v banliste

### ISSUE THREAD

**Issue by Jimmi08** [e107translations/Czech#7]
Bohužiaľ, hviezdičky už nefungujú.

![image](https://user-images.githubusercontent.com/5429548/44943789-946e7280-adcc-11e8-888b-e57bce851c8e.png)
![image](https://user-images.githubusercontent.com/5429548/44943796-a18b6180-adcc-11e8-8410-45e4e8ee4bc3.png)

**Comment by oxigeno2** [comment]
Nápověda jak vidím bude na delší den.

**Comment by Jimmi08** [comment]
Ono by to nevadilo, ale ten návod nefunguje a už neplatí. Hviezdičky nezaberajú.  V SK som tam myslím dala EN text, nechcelo sa mi s tým babrať.

**Comment by oxigeno2** [comment]
Hlavně nápověda nefunguje, podívám jestli funguje angličtině.

**Comment by oxigeno2** [comment]
Opraveno, přeloženo.
